### ISSUE TITLE
is this plugin compatible with redmine 1.4.4?

### ISSUE THREAD

**Issue by dhoelker** [ascendro/redmine_issue_reminder#22] opened 2012-07-19 13:15 UTC
get an internal sever error. production.log says:

<code>ActionView::TemplateError (No route matches {:project_id=>#<Project id: 5, name: "xxx", homepage: "xxx", is_public: true, parent_i$
54:
55:     <% if display_main_menu?(@project) %>
56:     <div id="main-menu">
57:         <%= render_main_menu(@project) %>
58:     </div>
59:     <% end %>
60: </div></code>

**Comment by cforce** [comment] 2012-07-19 22:14
No, the routes.rb in config folder is missing and needed since redmine.1.4

**Comment by MichaelKling** [comment] 2012-08-08 07:23
we will update our systems either to 1.4 or 2.0. its not clear yet if we try to take this plugin through it. 
biggest problem is that we dont have any ruby programmers internally and our external (bosko) has some big projects and no time for us anymore.

**Comment by MichaelKling** [comment] 2012-11-08 21:13
we have a redmine2.0 branch which is including a routes. maybe this can help? cforce you have any idea?

**Comment by cforce** [comment] 2012-11-08 23:13
Well then bring it online  here on github and maybe community will support you envolve it towards stable redmine 2.x support. Thats how opensource usaully works ;)

**Comment by MichaelKling** [comment] 2012-11-09 07:52
as i said we have the redmine2.0 branch - it's online and available here on github.
Link:  https://github.com/ascendro/redmine_issue_reminder/tree/redmine2.0

**Comment by cforce** [comment] 2012-11-09 16:44
Ah sorry, didN't check saw this.
Well the problem is that redmine 1.3 has no routes.rb, redmine 1.4 and redmine 2.x have differnt syntax. It's all incompatible. Realy bad thing. If ur branch wroks on redmine 2.0, dhoelker shall upgrade.Besides the routes.rb changes ther can be a lot other imcpmtibilities between 1.4 and 2.0. I would have to check all this things and downgrade. But i don't have time either - sorry. It doesn't make sense to invest such effort, as redmine 1.4 already is legacy. I also have todo upgrade, wer are still on 1.3. I will try to jump from 1.3 to 2.1. Hopefully i will get this done this year. Hopefully ur branch is stable ;)

**Comment by MichaelKling** [comment] 2012-11-09 16:58
its not stable as written in #23 - we dont have any ruby knowhow anymore in our company unfortunatly. 

but as the routes.rb is the only thing missing for 1.4 compatibility and the routes.rb in the 2.0 version (provided by a guy named Célestin Matte btw) is very small i thought that its very easy to port it.

**Comment by cforce** [comment] 2012-11-10 16:16
Well i don't have the plugin installed, i only can help you in theory.

The code shall look like this:

---

if Rails::VERSION::MAJOR < 3

# do redmine 1.4 routes here

  resources :reminders do
    post 'update_interval_values', :on => :collection
  end
  resources :query

  ActionController::Routing::Routes.draw do |map|
    map.connect 'url',:controller=> 'reminders', :action=> 'index'
    map.connect 'url',:controller=> 'reminders', :action=> 'settings'
    map.connect 'url',:controller=> 'reminders', :action=> 'others'
  end
end
else
 # do redmine 2.1 routes here
  match 'url' => 'view#method', :format => false, :as => 'view_method'

## end

Now you need to complete urls, parameters, and views names for all plugin has.

Please list all urls used for reminder views, maybe i can complete some more and u can help yourself then by try and error. It is not too difficult.

**Comment by MichaelKling** [comment] 2012-11-10 22:39
can you use the ones listed in the routes.rb of the redmine 2.0 branch?

That is:
 resources :reminders do
    post 'update_interval_values', :on => :collection
  end

  resources :query

**Comment by MichaelKling** [comment] 2012-12-20 14:23
thanks edysli! merged it into the branch. should be ok now.

**Closed as completed by MichaelKling** 2012-12-20 14:23 UTC
Labels: Version Compatibility
